[PORT FROM MAIN]wifi: Add multi-vendor support
BZ: 125764

This patch adds an extra layer of indirection to call vendor specific code in
the wifi HAL. The vendor specific code is called depending on
wlan.driver.vendor property, itself defined by ueventd when it receives a
specific modalias. Vendor specific code can also be disabled at compile time
without compilation error as enums and other array of functions pointers are
built at compile time.

Change-Id: I4dd608050a2549055eb3d4dab0b1369b7b8304f4
Orig-Change-Id: If430d833e64afea54f0f078558fffe4a196ae3f2
Category: device enablement
Domain: CWS.WIFI-Common
Origin: internal
Upstream-Candidate: yes
Signed-off-by: Quentin Casasnovas <quentinx.casasnovas@intel.com>
Reviewed-on: http://android.intel.com:8080/120542
Reviewed-by: Champciaux, Nicolas <nicolas.champciaux@intel.com>
Tested-by: Champciaux, Nicolas <nicolas.champciaux@intel.com>
Reviewed-by: cactus <cactus@intel.com>
Tested-by: cactus <cactus@intel.com>